// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/_render.ts";
import * as $1 from "./routes/api/prompt.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/App.tsx";

const manifest = {
  routes: {
    "./routes/_render.ts": $0,
    "./routes/api/prompt.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/App.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
